//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.03 at 05:21:23 PM EDT 
//


package com.zebra.pm.domainobjects.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="married" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dependent" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="education" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="selfEmployed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="creditHistory" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="propertyArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applicantIncome" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="coApplicantIncome" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="loanAmount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="loanAmountTerm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="loanStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deletion_time" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gender",
    "married",
    "dependent",
    "education",
    "selfEmployed",
    "creditHistory",
    "propertyArea",
    "applicantIncome",
    "coApplicantIncome",
    "loanAmount",
    "loanAmountTerm",
    "loanStatus",
    "deletionTime"
})
@XmlRootElement(name = "loanHistoryData")
public class LoanHistoryData {

    @XmlElement(required = true)
    protected String gender;
    @XmlElement(required = true)
    protected String married;
    protected int dependent;
    @XmlElement(required = true)
    protected String education;
    @XmlElement(required = true)
    protected String selfEmployed;
    protected int creditHistory;
    @XmlElement(required = true)
    protected String propertyArea;
    protected int applicantIncome;
    protected int coApplicantIncome;
    protected int loanAmount;
    protected int loanAmountTerm;
    @XmlElement(required = true)
    protected String loanStatus;
    @XmlElement(name = "deletion_time", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deletionTime;

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the married property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarried() {
        return married;
    }

    /**
     * Sets the value of the married property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarried(String value) {
        this.married = value;
    }

    /**
     * Gets the value of the dependent property.
     * 
     */
    public int getDependent() {
        return dependent;
    }

    /**
     * Sets the value of the dependent property.
     * 
     */
    public void setDependent(int value) {
        this.dependent = value;
    }

    /**
     * Gets the value of the education property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEducation() {
        return education;
    }

    /**
     * Sets the value of the education property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEducation(String value) {
        this.education = value;
    }

    /**
     * Gets the value of the selfEmployed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelfEmployed() {
        return selfEmployed;
    }

    /**
     * Sets the value of the selfEmployed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelfEmployed(String value) {
        this.selfEmployed = value;
    }

    /**
     * Gets the value of the creditHistory property.
     * 
     */
    public int getCreditHistory() {
        return creditHistory;
    }

    /**
     * Sets the value of the creditHistory property.
     * 
     */
    public void setCreditHistory(int value) {
        this.creditHistory = value;
    }

    /**
     * Gets the value of the propertyArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropertyArea() {
        return propertyArea;
    }

    /**
     * Sets the value of the propertyArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropertyArea(String value) {
        this.propertyArea = value;
    }

    /**
     * Gets the value of the applicantIncome property.
     * 
     */
    public int getApplicantIncome() {
        return applicantIncome;
    }

    /**
     * Sets the value of the applicantIncome property.
     * 
     */
    public void setApplicantIncome(int value) {
        this.applicantIncome = value;
    }

    /**
     * Gets the value of the coApplicantIncome property.
     * 
     */
    public int getCoApplicantIncome() {
        return coApplicantIncome;
    }

    /**
     * Sets the value of the coApplicantIncome property.
     * 
     */
    public void setCoApplicantIncome(int value) {
        this.coApplicantIncome = value;
    }

    /**
     * Gets the value of the loanAmount property.
     * 
     */
    public int getLoanAmount() {
        return loanAmount;
    }

    /**
     * Sets the value of the loanAmount property.
     * 
     */
    public void setLoanAmount(int value) {
        this.loanAmount = value;
    }

    /**
     * Gets the value of the loanAmountTerm property.
     * 
     */
    public int getLoanAmountTerm() {
        return loanAmountTerm;
    }

    /**
     * Sets the value of the loanAmountTerm property.
     * 
     */
    public void setLoanAmountTerm(int value) {
        this.loanAmountTerm = value;
    }

    /**
     * Gets the value of the loanStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoanStatus() {
        return loanStatus;
    }

    /**
     * Sets the value of the loanStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoanStatus(String value) {
        this.loanStatus = value;
    }

    /**
     * Gets the value of the deletionTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeletionTime() {
        return deletionTime;
    }

    /**
     * Sets the value of the deletionTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeletionTime(XMLGregorianCalendar value) {
        this.deletionTime = value;
    }

}
