//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.09 at 09:09:25 PM EDT 
//


package com.zebra.pm.domainobjects.services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zebra.pm.domainobjects.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zebra.pm.domainobjects.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoanDeletedData }
     * 
     */
    public LoanDeletedData createLoanDeletedData() {
        return new LoanDeletedData();
    }

    /**
     * Create an instance of {@link CustomerDeletedData }
     * 
     */
    public CustomerDeletedData createCustomerDeletedData() {
        return new CustomerDeletedData();
    }

}
