//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.03 at 05:21:23 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zebra.com/pm/domainobjects/services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zebra.pm.domainobjects.services;
